### ISSUE TITLE
libtoolize: command not found on darwin

### ISSUE THREAD

**Issue by yangwao** [mafintosh/node-sodium-prebuilt#10]
```
⫸  sudo npm install -g scuttlebot
/usr/local/bin/sbot -> /usr/local/lib/node_modules/scuttlebot/sbot.js

> sodium-prebuilt@1.0.22 install /usr/local/lib/node_modules/scuttlebot/node_modules/sodium-prebuilt
> prebuild --install --preinstall make

prebuild WARN install EACCES: permission denied, access '/Users/wao/.npm'
./autogen.sh: line 13: libtoolize: command not found
make: *** [configure] Error 127
prebuild ERR! build Error: make  failed with exit code 2
prebuild ERR! build     at Object.exports.spawnFailed (/usr/local/lib/node_modules/scuttlebot/node_modules/prebuild/error.js:31:10)
prebuild ERR! build     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/scuttlebot/node_modules/prebuild/util.js:116:14)
prebuild ERR! build     at emitTwo (events.js:106:13)
prebuild ERR! build     at ChildProcess.emit (events.js:191:7)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
/usr/local/lib
└── scuttlebot@9.6.0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sodium-prebuilt@1.0.22 (node_modules/scuttlebot/node_modules/sodium-prebuilt):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sodium-prebuilt@1.0.22 install: `prebuild --install --preinstall make`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 2
```
Then I tried 
`⫸  brew install libtool`
Which moves me to next error
```./autogen.sh: line 14: aclocal: command not found```
Ok, found this could fix thing
`⫸  brew install automake`
Which fixes the problem.
I think this packages should be requirements on Darwin/OSX before using this?
```
⫸  uname -a
Darwin VFTS352.local 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64
```

**Comment by av8ta** [comment]
I have the exact same problem on Windows when npm installing patchwork

**Comment by mafintosh** [comment]
Someone should migrate scuttlebutt to use the successor to this module, [sodium-native](https://github.com/mafintosh/sodium-native). Will fix all these issues as that has first class windows support
